# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77a94bb2db1d97883ab741533a069286addb083fe65750f09b6265c475d6f24e4481e052fbd2711b6e53a961db79d311b5839ed5ad8b1bc9f6d8d36219fead4e

test:
  secret_key_base: 3cab99e0b829d9c0e752eddce3976687f73e84549d5e17f2f06011c295ba027e944798b94d7b969eec39dfbf0cb0674d1d1301c9c0338733adfcb1c6304d9225

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
